schemas:
- description: Service
  id: service
  plural: services
  prefix: /sample/1.0
  schema:
    properties:
      id:
        description: ID
        permission:
        - create
        title: ID
        type: string
        unique: false
      name:
        description: Name
        permission:
        - create
        - update
        title: Name
        type: string
        unique: false
    propertiesOrder:
    - id
    - name
    type: object
    required: ['name']
  singular: service
  title: Services
